# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/c/Users/pc1/Documents/NetBeansProjects/threads

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/c/Users/pc1/Documents/NetBeansProjects/threads

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/pc1/Documents/NetBeansProjects/threads/CMakeFiles /cygdrive/c/Users/pc1/Documents/NetBeansProjects/threads/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/pc1/Documents/NetBeansProjects/threads/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named executables/ex_2

# Build rule for target.
executables/ex_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executables/ex_2
.PHONY : executables/ex_2

# fast build rule for target.
executables/ex_2/fast:
	$(MAKE) -f tworzenie_watkow/CMakeFiles/executables/ex_2.dir/build.make tworzenie_watkow/CMakeFiles/executables/ex_2.dir/build
.PHONY : executables/ex_2/fast

#=============================================================================
# Target rules for targets named executables/thread_create_11

# Build rule for target.
executables/thread_create_11: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executables/thread_create_11
.PHONY : executables/thread_create_11

# fast build rule for target.
executables/thread_create_11/fast:
	$(MAKE) -f tworzenie_watkow/CMakeFiles/executables/thread_create_11.dir/build.make tworzenie_watkow/CMakeFiles/executables/thread_create_11.dir/build
.PHONY : executables/thread_create_11/fast

#=============================================================================
# Target rules for targets named executables/thread_create_10

# Build rule for target.
executables/thread_create_10: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executables/thread_create_10
.PHONY : executables/thread_create_10

# fast build rule for target.
executables/thread_create_10/fast:
	$(MAKE) -f tworzenie_watkow/CMakeFiles/executables/thread_create_10.dir/build.make tworzenie_watkow/CMakeFiles/executables/thread_create_10.dir/build
.PHONY : executables/thread_create_10/fast

#=============================================================================
# Target rules for targets named executables/thread_create_9

# Build rule for target.
executables/thread_create_9: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executables/thread_create_9
.PHONY : executables/thread_create_9

# fast build rule for target.
executables/thread_create_9/fast:
	$(MAKE) -f tworzenie_watkow/CMakeFiles/executables/thread_create_9.dir/build.make tworzenie_watkow/CMakeFiles/executables/thread_create_9.dir/build
.PHONY : executables/thread_create_9/fast

#=============================================================================
# Target rules for targets named executables/thread_create_8

# Build rule for target.
executables/thread_create_8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executables/thread_create_8
.PHONY : executables/thread_create_8

# fast build rule for target.
executables/thread_create_8/fast:
	$(MAKE) -f tworzenie_watkow/CMakeFiles/executables/thread_create_8.dir/build.make tworzenie_watkow/CMakeFiles/executables/thread_create_8.dir/build
.PHONY : executables/thread_create_8/fast

#=============================================================================
# Target rules for targets named executables/thread_create_7

# Build rule for target.
executables/thread_create_7: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executables/thread_create_7
.PHONY : executables/thread_create_7

# fast build rule for target.
executables/thread_create_7/fast:
	$(MAKE) -f tworzenie_watkow/CMakeFiles/executables/thread_create_7.dir/build.make tworzenie_watkow/CMakeFiles/executables/thread_create_7.dir/build
.PHONY : executables/thread_create_7/fast

#=============================================================================
# Target rules for targets named executables/thread_create_2

# Build rule for target.
executables/thread_create_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executables/thread_create_2
.PHONY : executables/thread_create_2

# fast build rule for target.
executables/thread_create_2/fast:
	$(MAKE) -f tworzenie_watkow/CMakeFiles/executables/thread_create_2.dir/build.make tworzenie_watkow/CMakeFiles/executables/thread_create_2.dir/build
.PHONY : executables/thread_create_2/fast

#=============================================================================
# Target rules for targets named executables/ex_3

# Build rule for target.
executables/ex_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executables/ex_3
.PHONY : executables/ex_3

# fast build rule for target.
executables/ex_3/fast:
	$(MAKE) -f tworzenie_watkow/CMakeFiles/executables/ex_3.dir/build.make tworzenie_watkow/CMakeFiles/executables/ex_3.dir/build
.PHONY : executables/ex_3/fast

#=============================================================================
# Target rules for targets named executables/thread_create_1

# Build rule for target.
executables/thread_create_1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executables/thread_create_1
.PHONY : executables/thread_create_1

# fast build rule for target.
executables/thread_create_1/fast:
	$(MAKE) -f tworzenie_watkow/CMakeFiles/executables/thread_create_1.dir/build.make tworzenie_watkow/CMakeFiles/executables/thread_create_1.dir/build
.PHONY : executables/thread_create_1/fast

#=============================================================================
# Target rules for targets named executables/thread_create_4

# Build rule for target.
executables/thread_create_4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executables/thread_create_4
.PHONY : executables/thread_create_4

# fast build rule for target.
executables/thread_create_4/fast:
	$(MAKE) -f tworzenie_watkow/CMakeFiles/executables/thread_create_4.dir/build.make tworzenie_watkow/CMakeFiles/executables/thread_create_4.dir/build
.PHONY : executables/thread_create_4/fast

#=============================================================================
# Target rules for targets named executables/thread_create_3

# Build rule for target.
executables/thread_create_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executables/thread_create_3
.PHONY : executables/thread_create_3

# fast build rule for target.
executables/thread_create_3/fast:
	$(MAKE) -f tworzenie_watkow/CMakeFiles/executables/thread_create_3.dir/build.make tworzenie_watkow/CMakeFiles/executables/thread_create_3.dir/build
.PHONY : executables/thread_create_3/fast

#=============================================================================
# Target rules for targets named executables/thread_create_5

# Build rule for target.
executables/thread_create_5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executables/thread_create_5
.PHONY : executables/thread_create_5

# fast build rule for target.
executables/thread_create_5/fast:
	$(MAKE) -f tworzenie_watkow/CMakeFiles/executables/thread_create_5.dir/build.make tworzenie_watkow/CMakeFiles/executables/thread_create_5.dir/build
.PHONY : executables/thread_create_5/fast

#=============================================================================
# Target rules for targets named executables/thread_create_6

# Build rule for target.
executables/thread_create_6: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executables/thread_create_6
.PHONY : executables/thread_create_6

# fast build rule for target.
executables/thread_create_6/fast:
	$(MAKE) -f tworzenie_watkow/CMakeFiles/executables/thread_create_6.dir/build.make tworzenie_watkow/CMakeFiles/executables/thread_create_6.dir/build
.PHONY : executables/thread_create_6/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... executables/ex_2"
	@echo "... executables/thread_create_11"
	@echo "... executables/thread_create_10"
	@echo "... executables/thread_create_9"
	@echo "... executables/thread_create_8"
	@echo "... executables/thread_create_7"
	@echo "... executables/thread_create_2"
	@echo "... executables/ex_3"
	@echo "... executables/thread_create_1"
	@echo "... executables/thread_create_4"
	@echo "... executables/thread_create_3"
	@echo "... executables/thread_create_5"
	@echo "... executables/thread_create_6"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

